// Copyright 2018 The TensorFlow Authors. All Rights Reserved.
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//==============================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: tensorflow/compiler/xla/service/hlo_execution_profile_data.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HloExecutionProfileData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PrinterData     *HloProfilePrinterData `protobuf:"bytes,1,opt,name=printer_data,json=printerData,proto3" json:"printer_data,omitempty"`
	ProfileCounters []int64                `protobuf:"varint,2,rep,packed,name=profile_counters,json=profileCounters,proto3" json:"profile_counters,omitempty"`
}

func (x *HloExecutionProfileData) Reset() {
	*x = HloExecutionProfileData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tensorflow_compiler_xla_service_hlo_execution_profile_data_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HloExecutionProfileData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HloExecutionProfileData) ProtoMessage() {}

func (x *HloExecutionProfileData) ProtoReflect() protoreflect.Message {
	mi := &file_tensorflow_compiler_xla_service_hlo_execution_profile_data_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HloExecutionProfileData.ProtoReflect.Descriptor instead.
func (*HloExecutionProfileData) Descriptor() ([]byte, []int) {
	return file_tensorflow_compiler_xla_service_hlo_execution_profile_data_proto_rawDescGZIP(), []int{0}
}

func (x *HloExecutionProfileData) GetPrinterData() *HloProfilePrinterData {
	if x != nil {
		return x.PrinterData
	}
	return nil
}

func (x *HloExecutionProfileData) GetProfileCounters() []int64 {
	if x != nil {
		return x.ProfileCounters
	}
	return nil
}

var File_tensorflow_compiler_xla_service_hlo_execution_profile_data_proto protoreflect.FileDescriptor

var file_tensorflow_compiler_xla_service_hlo_execution_profile_data_proto_rawDesc = []byte{
	0x0a, 0x40, 0x74, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x66, 0x6c, 0x6f, 0x77, 0x2f, 0x63, 0x6f, 0x6d,
	0x70, 0x69, 0x6c, 0x65, 0x72, 0x2f, 0x78, 0x6c, 0x61, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2f, 0x68, 0x6c, 0x6f, 0x5f, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x03, 0x78, 0x6c, 0x61, 0x1a, 0x3e, 0x74, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x66,
	0x6c, 0x6f, 0x77, 0x2f, 0x63, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x72, 0x2f, 0x78, 0x6c, 0x61,
	0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x68, 0x6c, 0x6f, 0x5f, 0x70, 0x72, 0x6f,
	0x66, 0x69, 0x6c, 0x65, 0x5f, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x5f, 0x64, 0x61, 0x74,
	0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x83, 0x01, 0x0a, 0x17, 0x48, 0x6c, 0x6f, 0x45,
	0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x3d, 0x0a, 0x0c, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x5f, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x78, 0x6c, 0x61, 0x2e,
	0x48, 0x6c, 0x6f, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x50, 0x72, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0b, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x29, 0x0a, 0x10, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x03, 0x52, 0x0f, 0x70, 0x72,
	0x6f, 0x66, 0x69, 0x6c, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x42, 0x98, 0x01,
	0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x2e, 0x78, 0x6c, 0x61, 0x42, 0x1c, 0x48, 0x6c, 0x6f, 0x45, 0x78,
	0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x44, 0x61,
	0x74, 0x61, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x48, 0x02, 0x50, 0x01, 0x5a, 0x3e, 0x67, 0x69, 0x74,
	0x65, 0x65, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x71, 0x63, 0x69, 0x69, 0x70, 0x2d, 0x69, 0x63, 0x70,
	0x2f, 0x74, 0x66, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x6e, 0x67, 0x2f, 0x74, 0x65, 0x6e, 0x73,
	0x6f, 0x72, 0x66, 0x6c, 0x6f, 0x77, 0x2f, 0x63, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x72, 0x2f,
	0x78, 0x6c, 0x61, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0xf8, 0x01, 0x01, 0xa2, 0x02,
	0x03, 0x58, 0x58, 0x58, 0xaa, 0x02, 0x03, 0x58, 0x6c, 0x61, 0xca, 0x02, 0x03, 0x58, 0x6c, 0x61,
	0xe2, 0x02, 0x0f, 0x58, 0x6c, 0x61, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0xea, 0x02, 0x03, 0x58, 0x6c, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tensorflow_compiler_xla_service_hlo_execution_profile_data_proto_rawDescOnce sync.Once
	file_tensorflow_compiler_xla_service_hlo_execution_profile_data_proto_rawDescData = file_tensorflow_compiler_xla_service_hlo_execution_profile_data_proto_rawDesc
)

func file_tensorflow_compiler_xla_service_hlo_execution_profile_data_proto_rawDescGZIP() []byte {
	file_tensorflow_compiler_xla_service_hlo_execution_profile_data_proto_rawDescOnce.Do(func() {
		file_tensorflow_compiler_xla_service_hlo_execution_profile_data_proto_rawDescData = protoimpl.X.CompressGZIP(file_tensorflow_compiler_xla_service_hlo_execution_profile_data_proto_rawDescData)
	})
	return file_tensorflow_compiler_xla_service_hlo_execution_profile_data_proto_rawDescData
}

var file_tensorflow_compiler_xla_service_hlo_execution_profile_data_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tensorflow_compiler_xla_service_hlo_execution_profile_data_proto_goTypes = []interface{}{
	(*HloExecutionProfileData)(nil), // 0: xla.HloExecutionProfileData
	(*HloProfilePrinterData)(nil),   // 1: xla.HloProfilePrinterData
}
var file_tensorflow_compiler_xla_service_hlo_execution_profile_data_proto_depIdxs = []int32{
	1, // 0: xla.HloExecutionProfileData.printer_data:type_name -> xla.HloProfilePrinterData
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_tensorflow_compiler_xla_service_hlo_execution_profile_data_proto_init() }
func file_tensorflow_compiler_xla_service_hlo_execution_profile_data_proto_init() {
	if File_tensorflow_compiler_xla_service_hlo_execution_profile_data_proto != nil {
		return
	}
	file_tensorflow_compiler_xla_service_hlo_profile_printer_data_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_tensorflow_compiler_xla_service_hlo_execution_profile_data_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HloExecutionProfileData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tensorflow_compiler_xla_service_hlo_execution_profile_data_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tensorflow_compiler_xla_service_hlo_execution_profile_data_proto_goTypes,
		DependencyIndexes: file_tensorflow_compiler_xla_service_hlo_execution_profile_data_proto_depIdxs,
		MessageInfos:      file_tensorflow_compiler_xla_service_hlo_execution_profile_data_proto_msgTypes,
	}.Build()
	File_tensorflow_compiler_xla_service_hlo_execution_profile_data_proto = out.File
	file_tensorflow_compiler_xla_service_hlo_execution_profile_data_proto_rawDesc = nil
	file_tensorflow_compiler_xla_service_hlo_execution_profile_data_proto_goTypes = nil
	file_tensorflow_compiler_xla_service_hlo_execution_profile_data_proto_depIdxs = nil
}
