// Copyright 2022 The TensorFlow Authors. All Rights Reserved.
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//==============================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: tensorflow/compiler/xla/service/test_compilation_environment.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestCompilationEnvironment1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SomeFlag uint32 `protobuf:"varint,1,opt,name=some_flag,json=someFlag,proto3" json:"some_flag,omitempty"`
}

func (x *TestCompilationEnvironment1) Reset() {
	*x = TestCompilationEnvironment1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tensorflow_compiler_xla_service_test_compilation_environment_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestCompilationEnvironment1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestCompilationEnvironment1) ProtoMessage() {}

func (x *TestCompilationEnvironment1) ProtoReflect() protoreflect.Message {
	mi := &file_tensorflow_compiler_xla_service_test_compilation_environment_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestCompilationEnvironment1.ProtoReflect.Descriptor instead.
func (*TestCompilationEnvironment1) Descriptor() ([]byte, []int) {
	return file_tensorflow_compiler_xla_service_test_compilation_environment_proto_rawDescGZIP(), []int{0}
}

func (x *TestCompilationEnvironment1) GetSomeFlag() uint32 {
	if x != nil {
		return x.SomeFlag
	}
	return 0
}

type TestCompilationEnvironment2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SomeOtherFlag uint32 `protobuf:"varint,1,opt,name=some_other_flag,json=someOtherFlag,proto3" json:"some_other_flag,omitempty"`
}

func (x *TestCompilationEnvironment2) Reset() {
	*x = TestCompilationEnvironment2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tensorflow_compiler_xla_service_test_compilation_environment_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestCompilationEnvironment2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestCompilationEnvironment2) ProtoMessage() {}

func (x *TestCompilationEnvironment2) ProtoReflect() protoreflect.Message {
	mi := &file_tensorflow_compiler_xla_service_test_compilation_environment_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestCompilationEnvironment2.ProtoReflect.Descriptor instead.
func (*TestCompilationEnvironment2) Descriptor() ([]byte, []int) {
	return file_tensorflow_compiler_xla_service_test_compilation_environment_proto_rawDescGZIP(), []int{1}
}

func (x *TestCompilationEnvironment2) GetSomeOtherFlag() uint32 {
	if x != nil {
		return x.SomeOtherFlag
	}
	return 0
}

type TestCompilationEnvironment3 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AThirdFlag uint32 `protobuf:"varint,1,opt,name=a_third_flag,json=aThirdFlag,proto3" json:"a_third_flag,omitempty"`
}

func (x *TestCompilationEnvironment3) Reset() {
	*x = TestCompilationEnvironment3{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tensorflow_compiler_xla_service_test_compilation_environment_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestCompilationEnvironment3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestCompilationEnvironment3) ProtoMessage() {}

func (x *TestCompilationEnvironment3) ProtoReflect() protoreflect.Message {
	mi := &file_tensorflow_compiler_xla_service_test_compilation_environment_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestCompilationEnvironment3.ProtoReflect.Descriptor instead.
func (*TestCompilationEnvironment3) Descriptor() ([]byte, []int) {
	return file_tensorflow_compiler_xla_service_test_compilation_environment_proto_rawDescGZIP(), []int{2}
}

func (x *TestCompilationEnvironment3) GetAThirdFlag() uint32 {
	if x != nil {
		return x.AThirdFlag
	}
	return 0
}

var File_tensorflow_compiler_xla_service_test_compilation_environment_proto protoreflect.FileDescriptor

var file_tensorflow_compiler_xla_service_test_compilation_environment_proto_rawDesc = []byte{
	0x0a, 0x42, 0x74, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x66, 0x6c, 0x6f, 0x77, 0x2f, 0x63, 0x6f, 0x6d,
	0x70, 0x69, 0x6c, 0x65, 0x72, 0x2f, 0x78, 0x6c, 0x61, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x63, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x65, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x78, 0x6c, 0x61, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x22, 0x3a,
	0x0a, 0x1b, 0x54, 0x65, 0x73, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x31, 0x12, 0x1b, 0x0a,
	0x09, 0x73, 0x6f, 0x6d, 0x65, 0x5f, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x08, 0x73, 0x6f, 0x6d, 0x65, 0x46, 0x6c, 0x61, 0x67, 0x22, 0x45, 0x0a, 0x1b, 0x54, 0x65,
	0x73, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x6e, 0x76,
	0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x32, 0x12, 0x26, 0x0a, 0x0f, 0x73, 0x6f, 0x6d,
	0x65, 0x5f, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x5f, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0d, 0x73, 0x6f, 0x6d, 0x65, 0x4f, 0x74, 0x68, 0x65, 0x72, 0x46, 0x6c, 0x61,
	0x67, 0x22, 0x3f, 0x0a, 0x1b, 0x54, 0x65, 0x73, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x33,
	0x12, 0x20, 0x0a, 0x0c, 0x61, 0x5f, 0x74, 0x68, 0x69, 0x72, 0x64, 0x5f, 0x66, 0x6c, 0x61, 0x67,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x61, 0x54, 0x68, 0x69, 0x72, 0x64, 0x46, 0x6c,
	0x61, 0x67, 0x42, 0xb2, 0x01, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x2e, 0x78, 0x6c, 0x61, 0x2e, 0x74,
	0x65, 0x73, 0x74, 0x42, 0x1f, 0x54, 0x65, 0x73, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x48, 0x02, 0x50, 0x01, 0x5a, 0x3e, 0x67, 0x69, 0x74, 0x65, 0x65, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x71, 0x63, 0x69, 0x69, 0x70, 0x2d, 0x69, 0x63, 0x70, 0x2f, 0x74, 0x66,
	0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x6e, 0x67, 0x2f, 0x74, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x66,
	0x6c, 0x6f, 0x77, 0x2f, 0x63, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x72, 0x2f, 0x78, 0x6c, 0x61,
	0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0xa2, 0x02, 0x03, 0x58, 0x54, 0x58, 0xaa, 0x02,
	0x08, 0x58, 0x6c, 0x61, 0x2e, 0x54, 0x65, 0x73, 0x74, 0xca, 0x02, 0x08, 0x58, 0x6c, 0x61, 0x5c,
	0x54, 0x65, 0x73, 0x74, 0xe2, 0x02, 0x14, 0x58, 0x6c, 0x61, 0x5c, 0x54, 0x65, 0x73, 0x74, 0x5c,
	0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x09, 0x58, 0x6c,
	0x61, 0x3a, 0x3a, 0x54, 0x65, 0x73, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tensorflow_compiler_xla_service_test_compilation_environment_proto_rawDescOnce sync.Once
	file_tensorflow_compiler_xla_service_test_compilation_environment_proto_rawDescData = file_tensorflow_compiler_xla_service_test_compilation_environment_proto_rawDesc
)

func file_tensorflow_compiler_xla_service_test_compilation_environment_proto_rawDescGZIP() []byte {
	file_tensorflow_compiler_xla_service_test_compilation_environment_proto_rawDescOnce.Do(func() {
		file_tensorflow_compiler_xla_service_test_compilation_environment_proto_rawDescData = protoimpl.X.CompressGZIP(file_tensorflow_compiler_xla_service_test_compilation_environment_proto_rawDescData)
	})
	return file_tensorflow_compiler_xla_service_test_compilation_environment_proto_rawDescData
}

var file_tensorflow_compiler_xla_service_test_compilation_environment_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_tensorflow_compiler_xla_service_test_compilation_environment_proto_goTypes = []interface{}{
	(*TestCompilationEnvironment1)(nil), // 0: xla.test.TestCompilationEnvironment1
	(*TestCompilationEnvironment2)(nil), // 1: xla.test.TestCompilationEnvironment2
	(*TestCompilationEnvironment3)(nil), // 2: xla.test.TestCompilationEnvironment3
}
var file_tensorflow_compiler_xla_service_test_compilation_environment_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tensorflow_compiler_xla_service_test_compilation_environment_proto_init() }
func file_tensorflow_compiler_xla_service_test_compilation_environment_proto_init() {
	if File_tensorflow_compiler_xla_service_test_compilation_environment_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tensorflow_compiler_xla_service_test_compilation_environment_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestCompilationEnvironment1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tensorflow_compiler_xla_service_test_compilation_environment_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestCompilationEnvironment2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tensorflow_compiler_xla_service_test_compilation_environment_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestCompilationEnvironment3); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tensorflow_compiler_xla_service_test_compilation_environment_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tensorflow_compiler_xla_service_test_compilation_environment_proto_goTypes,
		DependencyIndexes: file_tensorflow_compiler_xla_service_test_compilation_environment_proto_depIdxs,
		MessageInfos:      file_tensorflow_compiler_xla_service_test_compilation_environment_proto_msgTypes,
	}.Build()
	File_tensorflow_compiler_xla_service_test_compilation_environment_proto = out.File
	file_tensorflow_compiler_xla_service_test_compilation_environment_proto_rawDesc = nil
	file_tensorflow_compiler_xla_service_test_compilation_environment_proto_goTypes = nil
	file_tensorflow_compiler_xla_service_test_compilation_environment_proto_depIdxs = nil
}
