// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: tensorflow/compiler/xla/tools/run_hlo_module.proto

package tools

import (
	xla "github.com/yangchnet/tf-serving/tensorflow/compiler/xla"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunHloModuleIterationLiterals struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Arguments used by the iteration.
	Arguments []*xla.LiteralProto `protobuf:"bytes,2,rep,name=arguments,proto3" json:"arguments,omitempty"`
	// Ressult of the iteration on the target platform.
	Result *xla.LiteralProto `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	// Result of the iteration on the reference platform.
	ReferenceResult *xla.LiteralProto `protobuf:"bytes,4,opt,name=reference_result,json=referenceResult,proto3" json:"reference_result,omitempty"`
}

func (x *RunHloModuleIterationLiterals) Reset() {
	*x = RunHloModuleIterationLiterals{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tensorflow_compiler_xla_tools_run_hlo_module_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunHloModuleIterationLiterals) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunHloModuleIterationLiterals) ProtoMessage() {}

func (x *RunHloModuleIterationLiterals) ProtoReflect() protoreflect.Message {
	mi := &file_tensorflow_compiler_xla_tools_run_hlo_module_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunHloModuleIterationLiterals.ProtoReflect.Descriptor instead.
func (*RunHloModuleIterationLiterals) Descriptor() ([]byte, []int) {
	return file_tensorflow_compiler_xla_tools_run_hlo_module_proto_rawDescGZIP(), []int{0}
}

func (x *RunHloModuleIterationLiterals) GetArguments() []*xla.LiteralProto {
	if x != nil {
		return x.Arguments
	}
	return nil
}

func (x *RunHloModuleIterationLiterals) GetResult() *xla.LiteralProto {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *RunHloModuleIterationLiterals) GetReferenceResult() *xla.LiteralProto {
	if x != nil {
		return x.ReferenceResult
	}
	return nil
}

type RunHloModuleLiterals struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Iterations of run hlo module.
	Iterations []*RunHloModuleIterationLiterals `protobuf:"bytes,1,rep,name=iterations,proto3" json:"iterations,omitempty"`
}

func (x *RunHloModuleLiterals) Reset() {
	*x = RunHloModuleLiterals{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tensorflow_compiler_xla_tools_run_hlo_module_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunHloModuleLiterals) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunHloModuleLiterals) ProtoMessage() {}

func (x *RunHloModuleLiterals) ProtoReflect() protoreflect.Message {
	mi := &file_tensorflow_compiler_xla_tools_run_hlo_module_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunHloModuleLiterals.ProtoReflect.Descriptor instead.
func (*RunHloModuleLiterals) Descriptor() ([]byte, []int) {
	return file_tensorflow_compiler_xla_tools_run_hlo_module_proto_rawDescGZIP(), []int{1}
}

func (x *RunHloModuleLiterals) GetIterations() []*RunHloModuleIterationLiterals {
	if x != nil {
		return x.Iterations
	}
	return nil
}

var File_tensorflow_compiler_xla_tools_run_hlo_module_proto protoreflect.FileDescriptor

var file_tensorflow_compiler_xla_tools_run_hlo_module_proto_rawDesc = []byte{
	0x0a, 0x32, 0x74, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x66, 0x6c, 0x6f, 0x77, 0x2f, 0x63, 0x6f, 0x6d,
	0x70, 0x69, 0x6c, 0x65, 0x72, 0x2f, 0x78, 0x6c, 0x61, 0x2f, 0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x2f,
	0x72, 0x75, 0x6e, 0x5f, 0x68, 0x6c, 0x6f, 0x5f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x78, 0x6c, 0x61, 0x1a, 0x26, 0x74, 0x65, 0x6e, 0x73, 0x6f,
	0x72, 0x66, 0x6c, 0x6f, 0x77, 0x2f, 0x63, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x72, 0x2f, 0x78,
	0x6c, 0x61, 0x2f, 0x78, 0x6c, 0x61, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xb9, 0x01, 0x0a, 0x1d, 0x52, 0x75, 0x6e, 0x48, 0x6c, 0x6f, 0x4d, 0x6f, 0x64, 0x75,
	0x6c, 0x65, 0x49, 0x74, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x74, 0x65, 0x72,
	0x61, 0x6c, 0x73, 0x12, 0x2f, 0x0a, 0x09, 0x61, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x78, 0x6c, 0x61, 0x2e, 0x4c, 0x69, 0x74,
	0x65, 0x72, 0x61, 0x6c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x09, 0x61, 0x72, 0x67, 0x75, 0x6d,
	0x65, 0x6e, 0x74, 0x73, 0x12, 0x29, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x78, 0x6c, 0x61, 0x2e, 0x4c, 0x69, 0x74, 0x65, 0x72,
	0x61, 0x6c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x3c, 0x0a, 0x10, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x5f, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x78, 0x6c, 0x61, 0x2e,
	0x4c, 0x69, 0x74, 0x65, 0x72, 0x61, 0x6c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x0f, 0x72, 0x65,
	0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x5a, 0x0a,
	0x14, 0x52, 0x75, 0x6e, 0x48, 0x6c, 0x6f, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x4c, 0x69, 0x74,
	0x65, 0x72, 0x61, 0x6c, 0x73, 0x12, 0x42, 0x0a, 0x0a, 0x69, 0x74, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x78, 0x6c, 0x61, 0x2e,
	0x52, 0x75, 0x6e, 0x48, 0x6c, 0x6f, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x49, 0x74, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x74, 0x65, 0x72, 0x61, 0x6c, 0x73, 0x52, 0x0a, 0x69,
	0x74, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x42, 0x88, 0x01, 0x0a, 0x07, 0x63, 0x6f,
	0x6d, 0x2e, 0x78, 0x6c, 0x61, 0x42, 0x11, 0x52, 0x75, 0x6e, 0x48, 0x6c, 0x6f, 0x4d, 0x6f, 0x64,
	0x75, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x48, 0x02, 0x50, 0x01, 0x5a, 0x3c, 0x67, 0x69,
	0x74, 0x65, 0x65, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x71, 0x63, 0x69, 0x69, 0x70, 0x2d, 0x69, 0x63,
	0x70, 0x2f, 0x74, 0x66, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x6e, 0x67, 0x2f, 0x74, 0x65, 0x6e,
	0x73, 0x6f, 0x72, 0x66, 0x6c, 0x6f, 0x77, 0x2f, 0x63, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x72,
	0x2f, 0x78, 0x6c, 0x61, 0x2f, 0x74, 0x6f, 0x6f, 0x6c, 0x73, 0xa2, 0x02, 0x03, 0x58, 0x58, 0x58,
	0xaa, 0x02, 0x03, 0x58, 0x6c, 0x61, 0xca, 0x02, 0x03, 0x58, 0x6c, 0x61, 0xe2, 0x02, 0x0f, 0x58,
	0x6c, 0x61, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02,
	0x03, 0x58, 0x6c, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tensorflow_compiler_xla_tools_run_hlo_module_proto_rawDescOnce sync.Once
	file_tensorflow_compiler_xla_tools_run_hlo_module_proto_rawDescData = file_tensorflow_compiler_xla_tools_run_hlo_module_proto_rawDesc
)

func file_tensorflow_compiler_xla_tools_run_hlo_module_proto_rawDescGZIP() []byte {
	file_tensorflow_compiler_xla_tools_run_hlo_module_proto_rawDescOnce.Do(func() {
		file_tensorflow_compiler_xla_tools_run_hlo_module_proto_rawDescData = protoimpl.X.CompressGZIP(file_tensorflow_compiler_xla_tools_run_hlo_module_proto_rawDescData)
	})
	return file_tensorflow_compiler_xla_tools_run_hlo_module_proto_rawDescData
}

var file_tensorflow_compiler_xla_tools_run_hlo_module_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_tensorflow_compiler_xla_tools_run_hlo_module_proto_goTypes = []interface{}{
	(*RunHloModuleIterationLiterals)(nil), // 0: xla.RunHloModuleIterationLiterals
	(*RunHloModuleLiterals)(nil),          // 1: xla.RunHloModuleLiterals
	(*xla.LiteralProto)(nil),              // 2: xla.LiteralProto
}
var file_tensorflow_compiler_xla_tools_run_hlo_module_proto_depIdxs = []int32{
	2, // 0: xla.RunHloModuleIterationLiterals.arguments:type_name -> xla.LiteralProto
	2, // 1: xla.RunHloModuleIterationLiterals.result:type_name -> xla.LiteralProto
	2, // 2: xla.RunHloModuleIterationLiterals.reference_result:type_name -> xla.LiteralProto
	0, // 3: xla.RunHloModuleLiterals.iterations:type_name -> xla.RunHloModuleIterationLiterals
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_tensorflow_compiler_xla_tools_run_hlo_module_proto_init() }
func file_tensorflow_compiler_xla_tools_run_hlo_module_proto_init() {
	if File_tensorflow_compiler_xla_tools_run_hlo_module_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tensorflow_compiler_xla_tools_run_hlo_module_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunHloModuleIterationLiterals); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tensorflow_compiler_xla_tools_run_hlo_module_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunHloModuleLiterals); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tensorflow_compiler_xla_tools_run_hlo_module_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tensorflow_compiler_xla_tools_run_hlo_module_proto_goTypes,
		DependencyIndexes: file_tensorflow_compiler_xla_tools_run_hlo_module_proto_depIdxs,
		MessageInfos:      file_tensorflow_compiler_xla_tools_run_hlo_module_proto_msgTypes,
	}.Build()
	File_tensorflow_compiler_xla_tools_run_hlo_module_proto = out.File
	file_tensorflow_compiler_xla_tools_run_hlo_module_proto_rawDesc = nil
	file_tensorflow_compiler_xla_tools_run_hlo_module_proto_goTypes = nil
	file_tensorflow_compiler_xla_tools_run_hlo_module_proto_depIdxs = nil
}
