// Copyright 2022 The TensorFlow Authors. All Rights Reserved.
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//==============================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: tensorflow/compiler/xla/runtime/runner/runner.proto

package runner

import (
	xla "gitee.com/qciip-icp/tf-serving/tensorflow/compiler/xla"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScalarProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Value:
	//
	//	*ScalarProto_I32
	//	*ScalarProto_I64
	Value isScalarProto_Value `protobuf_oneof:"value"`
}

func (x *ScalarProto) Reset() {
	*x = ScalarProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tensorflow_compiler_xla_runtime_runner_runner_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScalarProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScalarProto) ProtoMessage() {}

func (x *ScalarProto) ProtoReflect() protoreflect.Message {
	mi := &file_tensorflow_compiler_xla_runtime_runner_runner_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScalarProto.ProtoReflect.Descriptor instead.
func (*ScalarProto) Descriptor() ([]byte, []int) {
	return file_tensorflow_compiler_xla_runtime_runner_runner_proto_rawDescGZIP(), []int{0}
}

func (m *ScalarProto) GetValue() isScalarProto_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *ScalarProto) GetI32() int32 {
	if x, ok := x.GetValue().(*ScalarProto_I32); ok {
		return x.I32
	}
	return 0
}

func (x *ScalarProto) GetI64() int64 {
	if x, ok := x.GetValue().(*ScalarProto_I64); ok {
		return x.I64
	}
	return 0
}

type isScalarProto_Value interface {
	isScalarProto_Value()
}

type ScalarProto_I32 struct {
	I32 int32 `protobuf:"varint,1,opt,name=i32,proto3,oneof"`
}

type ScalarProto_I64 struct {
	I64 int64 `protobuf:"varint,2,opt,name=i64,proto3,oneof"`
}

func (*ScalarProto_I32) isScalarProto_Value() {}

func (*ScalarProto_I64) isScalarProto_Value() {}

type TensorProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dtype    xla.PrimitiveType `protobuf:"varint,1,opt,name=dtype,proto3,enum=xla.PrimitiveType" json:"dtype,omitempty"`
	Offset   int64             `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Sizes    []int64           `protobuf:"varint,3,rep,packed,name=sizes,proto3" json:"sizes,omitempty"`
	Strides  []int64           `protobuf:"varint,4,rep,packed,name=strides,proto3" json:"strides,omitempty"`
	Inout    bool              `protobuf:"varint,5,opt,name=inout,proto3" json:"inout,omitempty"`
	Contents []byte            `protobuf:"bytes,6,opt,name=contents,proto3" json:"contents,omitempty"`
}

func (x *TensorProto) Reset() {
	*x = TensorProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tensorflow_compiler_xla_runtime_runner_runner_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TensorProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TensorProto) ProtoMessage() {}

func (x *TensorProto) ProtoReflect() protoreflect.Message {
	mi := &file_tensorflow_compiler_xla_runtime_runner_runner_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TensorProto.ProtoReflect.Descriptor instead.
func (*TensorProto) Descriptor() ([]byte, []int) {
	return file_tensorflow_compiler_xla_runtime_runner_runner_proto_rawDescGZIP(), []int{1}
}

func (x *TensorProto) GetDtype() xla.PrimitiveType {
	if x != nil {
		return x.Dtype
	}
	return xla.PrimitiveType(0)
}

func (x *TensorProto) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *TensorProto) GetSizes() []int64 {
	if x != nil {
		return x.Sizes
	}
	return nil
}

func (x *TensorProto) GetStrides() []int64 {
	if x != nil {
		return x.Strides
	}
	return nil
}

func (x *TensorProto) GetInout() bool {
	if x != nil {
		return x.Inout
	}
	return false
}

func (x *TensorProto) GetContents() []byte {
	if x != nil {
		return x.Contents
	}
	return nil
}

type ArgumentProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Argument:
	//
	//	*ArgumentProto_Scalar
	//	*ArgumentProto_Tensor
	Argument isArgumentProto_Argument `protobuf_oneof:"argument"`
}

func (x *ArgumentProto) Reset() {
	*x = ArgumentProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tensorflow_compiler_xla_runtime_runner_runner_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArgumentProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArgumentProto) ProtoMessage() {}

func (x *ArgumentProto) ProtoReflect() protoreflect.Message {
	mi := &file_tensorflow_compiler_xla_runtime_runner_runner_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArgumentProto.ProtoReflect.Descriptor instead.
func (*ArgumentProto) Descriptor() ([]byte, []int) {
	return file_tensorflow_compiler_xla_runtime_runner_runner_proto_rawDescGZIP(), []int{2}
}

func (m *ArgumentProto) GetArgument() isArgumentProto_Argument {
	if m != nil {
		return m.Argument
	}
	return nil
}

func (x *ArgumentProto) GetScalar() *ScalarProto {
	if x, ok := x.GetArgument().(*ArgumentProto_Scalar); ok {
		return x.Scalar
	}
	return nil
}

func (x *ArgumentProto) GetTensor() *TensorProto {
	if x, ok := x.GetArgument().(*ArgumentProto_Tensor); ok {
		return x.Tensor
	}
	return nil
}

type isArgumentProto_Argument interface {
	isArgumentProto_Argument()
}

type ArgumentProto_Scalar struct {
	Scalar *ScalarProto `protobuf:"bytes,1,opt,name=scalar,proto3,oneof"`
}

type ArgumentProto_Tensor struct {
	Tensor *TensorProto `protobuf:"bytes,2,opt,name=tensor,proto3,oneof"`
}

func (*ArgumentProto_Scalar) isArgumentProto_Argument() {}

func (*ArgumentProto_Tensor) isArgumentProto_Argument() {}

type ResultProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Result:
	//
	//	*ResultProto_Scalar
	//	*ResultProto_Tensor
	Result isResultProto_Result `protobuf_oneof:"result"`
}

func (x *ResultProto) Reset() {
	*x = ResultProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tensorflow_compiler_xla_runtime_runner_runner_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResultProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultProto) ProtoMessage() {}

func (x *ResultProto) ProtoReflect() protoreflect.Message {
	mi := &file_tensorflow_compiler_xla_runtime_runner_runner_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultProto.ProtoReflect.Descriptor instead.
func (*ResultProto) Descriptor() ([]byte, []int) {
	return file_tensorflow_compiler_xla_runtime_runner_runner_proto_rawDescGZIP(), []int{3}
}

func (m *ResultProto) GetResult() isResultProto_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (x *ResultProto) GetScalar() *ScalarProto {
	if x, ok := x.GetResult().(*ResultProto_Scalar); ok {
		return x.Scalar
	}
	return nil
}

func (x *ResultProto) GetTensor() *TensorProto {
	if x, ok := x.GetResult().(*ResultProto_Tensor); ok {
		return x.Tensor
	}
	return nil
}

type isResultProto_Result interface {
	isResultProto_Result()
}

type ResultProto_Scalar struct {
	Scalar *ScalarProto `protobuf:"bytes,1,opt,name=scalar,proto3,oneof"`
}

type ResultProto_Tensor struct {
	Tensor *TensorProto `protobuf:"bytes,2,opt,name=tensor,proto3,oneof"`
}

func (*ResultProto_Scalar) isResultProto_Result() {}

func (*ResultProto_Tensor) isResultProto_Result() {}

type ArgumentsProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Arguments []*ArgumentProto `protobuf:"bytes,1,rep,name=arguments,proto3" json:"arguments,omitempty"`
}

func (x *ArgumentsProto) Reset() {
	*x = ArgumentsProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tensorflow_compiler_xla_runtime_runner_runner_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArgumentsProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArgumentsProto) ProtoMessage() {}

func (x *ArgumentsProto) ProtoReflect() protoreflect.Message {
	mi := &file_tensorflow_compiler_xla_runtime_runner_runner_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArgumentsProto.ProtoReflect.Descriptor instead.
func (*ArgumentsProto) Descriptor() ([]byte, []int) {
	return file_tensorflow_compiler_xla_runtime_runner_runner_proto_rawDescGZIP(), []int{4}
}

func (x *ArgumentsProto) GetArguments() []*ArgumentProto {
	if x != nil {
		return x.Arguments
	}
	return nil
}

type ResultsProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*ResultProto `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *ResultsProto) Reset() {
	*x = ResultsProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tensorflow_compiler_xla_runtime_runner_runner_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResultsProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultsProto) ProtoMessage() {}

func (x *ResultsProto) ProtoReflect() protoreflect.Message {
	mi := &file_tensorflow_compiler_xla_runtime_runner_runner_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultsProto.ProtoReflect.Descriptor instead.
func (*ResultsProto) Descriptor() ([]byte, []int) {
	return file_tensorflow_compiler_xla_runtime_runner_runner_proto_rawDescGZIP(), []int{5}
}

func (x *ResultsProto) GetResults() []*ResultProto {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_tensorflow_compiler_xla_runtime_runner_runner_proto protoreflect.FileDescriptor

var file_tensorflow_compiler_xla_runtime_runner_runner_proto_rawDesc = []byte{
	0x0a, 0x33, 0x74, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x66, 0x6c, 0x6f, 0x77, 0x2f, 0x63, 0x6f, 0x6d,
	0x70, 0x69, 0x6c, 0x65, 0x72, 0x2f, 0x78, 0x6c, 0x61, 0x2f, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d,
	0x65, 0x2f, 0x72, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x2f, 0x72, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x78, 0x6c, 0x61, 0x1a, 0x26, 0x74, 0x65, 0x6e, 0x73,
	0x6f, 0x72, 0x66, 0x6c, 0x6f, 0x77, 0x2f, 0x63, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x72, 0x2f,
	0x78, 0x6c, 0x61, 0x2f, 0x78, 0x6c, 0x61, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x3e, 0x0a, 0x0b, 0x53, 0x63, 0x61, 0x6c, 0x61, 0x72, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x12, 0x0a, 0x03, 0x69, 0x33, 0x32, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00,
	0x52, 0x03, 0x69, 0x33, 0x32, 0x12, 0x12, 0x0a, 0x03, 0x69, 0x36, 0x34, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x48, 0x00, 0x52, 0x03, 0x69, 0x36, 0x34, 0x42, 0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x22, 0xb1, 0x01, 0x0a, 0x0b, 0x54, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x28, 0x0a, 0x05, 0x64, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x12, 0x2e, 0x78, 0x6c, 0x61, 0x2e, 0x50, 0x72, 0x69, 0x6d, 0x69, 0x74, 0x69, 0x76,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x05, 0x64, 0x74, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6f, 0x66,
	0x66, 0x73, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x69, 0x7a, 0x65, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x03, 0x52, 0x05, 0x73, 0x69, 0x7a, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x74,
	0x72, 0x69, 0x64, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x03, 0x52, 0x07, 0x73, 0x74, 0x72,
	0x69, 0x64, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x6f, 0x75, 0x74, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x05, 0x69, 0x6e, 0x6f, 0x75, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x73, 0x0a, 0x0d, 0x41, 0x72, 0x67, 0x75, 0x6d, 0x65,
	0x6e, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x2a, 0x0a, 0x06, 0x73, 0x63, 0x61, 0x6c, 0x61,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x78, 0x6c, 0x61, 0x2e, 0x53, 0x63,
	0x61, 0x6c, 0x61, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x48, 0x00, 0x52, 0x06, 0x73, 0x63, 0x61,
	0x6c, 0x61, 0x72, 0x12, 0x2a, 0x0a, 0x06, 0x74, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x78, 0x6c, 0x61, 0x2e, 0x54, 0x65, 0x6e, 0x73, 0x6f, 0x72,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x48, 0x00, 0x52, 0x06, 0x74, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x42,
	0x0a, 0x0a, 0x08, 0x61, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x6f, 0x0a, 0x0b, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x2a, 0x0a, 0x06, 0x73, 0x63,
	0x61, 0x6c, 0x61, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x78, 0x6c, 0x61,
	0x2e, 0x53, 0x63, 0x61, 0x6c, 0x61, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x48, 0x00, 0x52, 0x06,
	0x73, 0x63, 0x61, 0x6c, 0x61, 0x72, 0x12, 0x2a, 0x0a, 0x06, 0x74, 0x65, 0x6e, 0x73, 0x6f, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x78, 0x6c, 0x61, 0x2e, 0x54, 0x65, 0x6e,
	0x73, 0x6f, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x48, 0x00, 0x52, 0x06, 0x74, 0x65, 0x6e, 0x73,
	0x6f, 0x72, 0x42, 0x08, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x42, 0x0a, 0x0e,
	0x41, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x30,
	0x0a, 0x09, 0x61, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x78, 0x6c, 0x61, 0x2e, 0x41, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x09, 0x61, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73,
	0x22, 0x3a, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x2a, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x78, 0x6c, 0x61, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x42, 0x8b, 0x01, 0x0a,
	0x07, 0x63, 0x6f, 0x6d, 0x2e, 0x78, 0x6c, 0x61, 0x42, 0x0b, 0x52, 0x75, 0x6e, 0x6e, 0x65, 0x72,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x48, 0x02, 0x50, 0x01, 0x5a, 0x45, 0x67, 0x69, 0x74, 0x65, 0x65,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x71, 0x63, 0x69, 0x69, 0x70, 0x2d, 0x69, 0x63, 0x70, 0x2f, 0x74,
	0x66, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x6e, 0x67, 0x2f, 0x74, 0x65, 0x6e, 0x73, 0x6f, 0x72,
	0x66, 0x6c, 0x6f, 0x77, 0x2f, 0x63, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x72, 0x2f, 0x78, 0x6c,
	0x61, 0x2f, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2f, 0x72, 0x75, 0x6e, 0x6e, 0x65, 0x72,
	0xa2, 0x02, 0x03, 0x58, 0x58, 0x58, 0xaa, 0x02, 0x03, 0x58, 0x6c, 0x61, 0xca, 0x02, 0x03, 0x58,
	0x6c, 0x61, 0xe2, 0x02, 0x0f, 0x58, 0x6c, 0x61, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x03, 0x58, 0x6c, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_tensorflow_compiler_xla_runtime_runner_runner_proto_rawDescOnce sync.Once
	file_tensorflow_compiler_xla_runtime_runner_runner_proto_rawDescData = file_tensorflow_compiler_xla_runtime_runner_runner_proto_rawDesc
)

func file_tensorflow_compiler_xla_runtime_runner_runner_proto_rawDescGZIP() []byte {
	file_tensorflow_compiler_xla_runtime_runner_runner_proto_rawDescOnce.Do(func() {
		file_tensorflow_compiler_xla_runtime_runner_runner_proto_rawDescData = protoimpl.X.CompressGZIP(file_tensorflow_compiler_xla_runtime_runner_runner_proto_rawDescData)
	})
	return file_tensorflow_compiler_xla_runtime_runner_runner_proto_rawDescData
}

var file_tensorflow_compiler_xla_runtime_runner_runner_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_tensorflow_compiler_xla_runtime_runner_runner_proto_goTypes = []interface{}{
	(*ScalarProto)(nil),    // 0: xla.ScalarProto
	(*TensorProto)(nil),    // 1: xla.TensorProto
	(*ArgumentProto)(nil),  // 2: xla.ArgumentProto
	(*ResultProto)(nil),    // 3: xla.ResultProto
	(*ArgumentsProto)(nil), // 4: xla.ArgumentsProto
	(*ResultsProto)(nil),   // 5: xla.ResultsProto
	(xla.PrimitiveType)(0), // 6: xla.PrimitiveType
}
var file_tensorflow_compiler_xla_runtime_runner_runner_proto_depIdxs = []int32{
	6, // 0: xla.TensorProto.dtype:type_name -> xla.PrimitiveType
	0, // 1: xla.ArgumentProto.scalar:type_name -> xla.ScalarProto
	1, // 2: xla.ArgumentProto.tensor:type_name -> xla.TensorProto
	0, // 3: xla.ResultProto.scalar:type_name -> xla.ScalarProto
	1, // 4: xla.ResultProto.tensor:type_name -> xla.TensorProto
	2, // 5: xla.ArgumentsProto.arguments:type_name -> xla.ArgumentProto
	3, // 6: xla.ResultsProto.results:type_name -> xla.ResultProto
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_tensorflow_compiler_xla_runtime_runner_runner_proto_init() }
func file_tensorflow_compiler_xla_runtime_runner_runner_proto_init() {
	if File_tensorflow_compiler_xla_runtime_runner_runner_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tensorflow_compiler_xla_runtime_runner_runner_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScalarProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tensorflow_compiler_xla_runtime_runner_runner_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TensorProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tensorflow_compiler_xla_runtime_runner_runner_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArgumentProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tensorflow_compiler_xla_runtime_runner_runner_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResultProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tensorflow_compiler_xla_runtime_runner_runner_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArgumentsProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tensorflow_compiler_xla_runtime_runner_runner_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResultsProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_tensorflow_compiler_xla_runtime_runner_runner_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*ScalarProto_I32)(nil),
		(*ScalarProto_I64)(nil),
	}
	file_tensorflow_compiler_xla_runtime_runner_runner_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*ArgumentProto_Scalar)(nil),
		(*ArgumentProto_Tensor)(nil),
	}
	file_tensorflow_compiler_xla_runtime_runner_runner_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*ResultProto_Scalar)(nil),
		(*ResultProto_Tensor)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tensorflow_compiler_xla_runtime_runner_runner_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tensorflow_compiler_xla_runtime_runner_runner_proto_goTypes,
		DependencyIndexes: file_tensorflow_compiler_xla_runtime_runner_runner_proto_depIdxs,
		MessageInfos:      file_tensorflow_compiler_xla_runtime_runner_runner_proto_msgTypes,
	}.Build()
	File_tensorflow_compiler_xla_runtime_runner_runner_proto = out.File
	file_tensorflow_compiler_xla_runtime_runner_runner_proto_rawDesc = nil
	file_tensorflow_compiler_xla_runtime_runner_runner_proto_goTypes = nil
	file_tensorflow_compiler_xla_runtime_runner_runner_proto_depIdxs = nil
}
